# Generated by Django 5.2.8 on 2025-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('root_path', models.CharField(max_length=500, verbose_name='Корневой внешний путь')),
                ('folder_name', models.CharField(max_length=200, verbose_name='Имя папки проекта')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
