# Generated by Django 5.2.8 on 2025-12-09 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'verbose_name': 'Project member', 'verbose_name_plural': 'Project members'},
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='role',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
