# Generated by Django 5.2.8 on 2025-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPSRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_name', models.CharField(max_length=255, unique=True)),
                ('record_start', models.IntegerField(default=0)),
                ('record_end', models.IntegerField(default=0)),
                ('line_start', models.IntegerField(default=0)),
                ('line_end', models.IntegerField(default=0)),
                ('point_start', models.IntegerField(default=0)),
                ('point_end', models.IntegerField(default=0)),
                ('point_idx_start', models.IntegerField(default=0)),
                ('point_idx_end', models.IntegerField(default=0)),
                ('point_code_start', models.IntegerField(default=0)),
                ('point_code_end', models.IntegerField(default=0)),
                ('static_start', models.IntegerField(default=0)),
                ('static_end', models.IntegerField(default=0)),
                ('point_depth_start', models.IntegerField(default=0)),
                ('point_depth_end', models.IntegerField(default=0)),
                ('datum_start', models.IntegerField(default=0)),
                ('datum_end', models.IntegerField(default=0)),
                ('uphole_start', models.IntegerField(default=0)),
                ('uphole_end', models.IntegerField(default=0)),
                ('water_depth_start', models.IntegerField(default=0)),
                ('water_depth_end', models.IntegerField(default=0)),
                ('easting_start', models.IntegerField(default=0)),
                ('easting_end', models.IntegerField(default=0)),
                ('northing_start', models.IntegerField(default=0)),
                ('northing_end', models.IntegerField(default=0)),
                ('elevation_start', models.IntegerField(default=0)),
                ('elevation_end', models.IntegerField(default=0)),
                ('jday_start', models.IntegerField(default=0)),
                ('jday_end', models.IntegerField(default=0)),
                ('hour_start', models.IntegerField(default=0)),
                ('hour_end', models.IntegerField(default=0)),
                ('minute_start', models.IntegerField(default=0)),
                ('minute_end', models.IntegerField(default=0)),
                ('second_start', models.IntegerField(default=0)),
                ('second_end', models.IntegerField(default=0)),
                ('msecond_start', models.IntegerField(default=0)),
                ('msecond_end', models.IntegerField(default=0)),
                ('default_format', models.BooleanField(default=False)),
            ],
        ),
    ]
