# Generated by Django 5.2.8 on 2026-02-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_deleted_at_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='theme_mode',
            field=models.CharField(default='dark', max_length=8),
        ),
    ]
