# Generated by Django 5.2.8 on 2026-03-21 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_seed_spsrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('profile_time', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('point_count', models.PositiveIntegerField(default=0)),
                ('max_depth', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svp_profiles', to='core.project')),
            ],
            options={
                'ordering': ['-profile_time', '-created_at', '-id'],
                'unique_together': {('project', 'name', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='SVPPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(default=1)),
                ('depth', models.FloatField()),
                ('velocity', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='svp.svpprofile')),
            ],
            options={
                'ordering': ['seq_no', 'id'],
            },
        ),
    ]
