# Generated by Django 5.2.8 on 2026-03-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='svpprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='svpprofile',
            name='project',
        ),
        migrations.DeleteModel(
            name='SVPPoint',
        ),
        migrations.DeleteModel(
            name='SVPProfile',
        ),
    ]
