--Create file tables
CREATE TABLE  IF NOT EXISTS  Files (
                                ID INTEGER PRIMARY KEY AUTOINCREMENT,
                                FileName TEXT UNIQUE,
                                UNIQUE(FileName, ID)
                               );
--Create solution table
CREATE TABLE  IF NOT EXISTS  Solutions (
                                   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                                   Solution TEXT NOT NULL,
                                   UNIQUE(Solution)
                                  );
CREATE TABLE  IF NOT EXISTS  project_vessels (
                           ID INTEGER PRIMARY KEY AUTOINCREMENT,
                           Name TEXT NOT NULL UNIQUE,
                           Description TEXT,
                           IMONum TEXT NOT NULL UNIQUE
                       );
CREATE TABLE  IF NOT EXISTS  ROVS_CONFIG
                ("rov1_name" TEXT DEFAULT 'ROV1',
                 "rov2_name" TEXT DEFAULT 'ROV2',
                 "gnss1_name" TEXT DEFAULT 'GNSS1',
                 "gnss2_name" TEXT DEFAULT 'GNSS2'
                );
--Create receiver preplot tables
CREATE TABLE  IF NOT EXISTS  RLPreplot (
                              ID INTEGER PRIMARY KEY AUTOINCREMENT,
                              Line INTEGER,
                              TierLine INTEGER UNIQUE, -- Unique constraint added to TierLine column
                              Points INTEGER,
                              UPoints INTEGER,
                              FirstPoint INTEGER,
                              LastPoint INTEGER,
                              MinPoint INTEGER,
                              MaxPoint INTEGER,
                              RealStartX REAL,
                              RealStartY REAL,
                              RealEndX REAL,
                              RealEndY REAL,
                              StartX REAL,
                              StartY REAL,
                              EndX REAL,
                              EndY REAL,
                              LineLength REAL DEFAULT 0,
                              RealLineLength REAL DEFAULT 0,
                              LineBearing REAL DEFAULT 0,
                              CalcLineBearing REAL DEFAULT 0,

                              isLineClicked INTEGER DEFAULT 0,
                              isLineDeployed INTEGER DEFAULT 0,
                              isLinePinged INTEGER DEFAULT 0,
                              isLineRecovered INTEGER DEFAULT 0,
                              isMessaged INTEGER DEFAULT 0,
                              isValidated INTEGER DEFAULT 0,

                              RPIndex INTEGER DEFAULT 0,
                              Tier INTEGER DEFAULT 1,

                              PointsDep INTEGER DEFAULT 0,
                              PointsRec INTEGER DEFAULT 0,
                              PointsProc INTEGER DEFAULT 0,

                              Comments TEXT DEFAULT '',
                              Message Text DEFAULT '',
                              ValidationTime TEXT,

                              Spare1 INTEGER DEFAULT 0,
                              Spare2 INTEGER DEFAULT 0,
                              Spare3 INTEGER DEFAULT 0,

                              Spare4 REAL DEFAULT 0,
                              Spare5 REAL DEFAULT 0,
                              Spare6 REAL DEFAULT 0,

                              File_FK INTEGER,
                              FOREIGN KEY (File_FK) REFERENCES Files(ID)  ON DELETE CASCADE,
                              UNIQUE (TierLine, ID)
                         );
CREATE TABLE  IF NOT EXISTS  RPPreplot (
                              ID INTEGER PRIMARY KEY AUTOINCREMENT,
                              Line_FK INTEGER,
                              Line INTEGER,
                              TierLine INTEGER,
                              Point INTEGER,
                              PointCode TEXT DEFAULT "",
                              PointIndex INTEGER DEFAULT 1,
                              LinePoint INTEGER DEFAULT 0,
                              TLinePoint REAL,
                              LinePointIndex REAL DEFAULT 0,
                              TLinePointIndex REAL DEFAULT 0,
                              X REAL,
                              Y REAL,
                              Z REAL,
                              LineBearing REAL DEFAULT 0,
                              Tier INTEGER DEFAULT 1,
                              Spare1 INTEGER DEFAULT 0,
                              Spare2 INTEGER DEFAULT 0,
                              Spare3 INTEGER DEFAULT 0,
                              File_FK INTEGER,
                              FOREIGN KEY (Line_FK) REFERENCES RLPreplot(ID) ON DELETE CASCADE,
                              FOREIGN KEY (File_FK) REFERENCES Files(ID) ON DELETE CASCADE,
                              UNIQUE(ID)
                            );
CREATE UNIQUE INDEX IF NOT EXISTS ux_rppreplot
       ON RPPreplot (Tier, Line, Point, PointIndex);
--Create source preplot tables
CREATE TABLE  IF NOT EXISTS  SLPreplot (
                              ID INTEGER PRIMARY KEY AUTOINCREMENT,
                              Line INTEGER,
                              TierLine INTEGER UNIQUE, -- Unique constraint added to TierLine column
                              Points INTEGER,
                              UPoints INTEGER,
                              FirstPoint INTEGER,
                              LastPoint INTEGER,
                              MinPoint INTEGER,
                              MaxPoint INTEGER,
                              RealStartX REAL,
                              RealStartY REAL,
                              RealEndX REAL,
                              RealEndY REAL,
                              StartX REAL,
                              StartY REAL,
                              EndX REAL,
                              EndY REAL,
                              LineLength REAL DEFAULT 0,
                              RealLineLength REAL DEFAULT 0,
                              LineBearing REAL DEFAULT 0,
                              CalcLineBearing REAL DEFAULT 0,

                              isLineClicked INTEGER DEFAULT 0,
                              isLineDeployed INTEGER DEFAULT 0,
                              isLinePinged INTEGER DEFAULT 0,
                              isLineRecovered INTEGER DEFAULT 0,
                              isMessaged INTEGER DEFAULT 0,
                              isValidated INTEGER DEFAULT 0,

                              RPIndex INTEGER DEFAULT 0,
                              Tier INTEGER DEFAULT 1,

                              PointsDep INTEGER DEFAULT 0,
                              PointsRec INTEGER DEFAULT 0,
                              PointsProc INTEGER DEFAULT 0,

                              Comments TEXT DEFAULT '',
                              Message Text DEFAULT '',
                              ValidationTime TEXT,

                              Spare1 INTEGER DEFAULT 0,
                              Spare2 INTEGER DEFAULT 0,
                              Spare3 INTEGER DEFAULT 0,

                              Spare4 REAL DEFAULT 0,
                              Spare5 REAL DEFAULT 0,
                              Spare6 REAL DEFAULT 0,

                              File_FK INTEGER,
                              FOREIGN KEY (File_FK) REFERENCES Files(ID)  ON DELETE CASCADE,
                              UNIQUE (TierLine, ID)
                         );
CREATE TABLE  IF NOT EXISTS  SPPreplot (
                              ID INTEGER PRIMARY KEY AUTOINCREMENT,
                              Line_FK INTEGER,
                              Line INTEGER,
                              TierLine INTEGER,
                              Point INTEGER,
                              PointCode TEXT DEFAULT "",
                              PointIndex INTEGER DEFAULT 1,
                              LinePoint INTEGER DEFAULT 0,
                              TLinePoint REAL,
                              LinePointIndex REAL DEFAULT 0,
                              TLinePointIndex REAL DEFAULT 0,
                              X REAL,
                              Y REAL,
                              Z REAL,
                              LineBearing REAL DEFAULT 0,
                              Tier INTEGER DEFAULT 1,
                              Spare1 INTEGER DEFAULT 0,
                              Spare2 INTEGER DEFAULT 0,
                              Spare3 INTEGER DEFAULT 0,
                              File_FK INTEGER,
                              FOREIGN KEY (Line_FK) REFERENCES SLPreplot(ID) ON DELETE CASCADE,
                              FOREIGN KEY (File_FK) REFERENCES Files(ID) ON DELETE CASCADE,
                              UNIQUE(ID)
                            );
CREATE UNIQUE INDEX IF NOT EXISTS ux_sppreplot
       ON SPPreplot (Tier, Line, Point, PointIndex);
-- for fast WHERE Line_FK = ?
CREATE INDEX IF NOT EXISTS ix_sppreplot_linefk ON SPPreplot(Line_FK);
CREATE INDEX IF NOT EXISTS ix_rppreplot_linefk ON RPPreplot(Line_FK);
-- for fast ORDER BY Point and fast MIN/MAX by Point
CREATE INDEX IF NOT EXISTS ix_sppreplot_linefk_point ON SPPreplot(Line_FK, Point);
CREATE INDEX IF NOT EXISTS ix_rppreplot_linefk_point ON RPPreplot(Line_FK, Point);

--Create DSR table
CREATE TABLE  IF NOT EXISTS  "DSR" (
                    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
                    "LinePointIdx" INTEGER UNIQUE,
                    "Line" INTEGER,
                    "Station" INTEGER,
                    "Node" TEXT,
                    "PreplotEasting" REAL,
                    "PreplotNorthing" REAL,
                    "ROV" TEXT,
                    "TimeStamp" TEXT,
                    "PrimaryEasting" REAL,
                    "Sigma" REAL,
                    "PrimaryNorthing" REAL,
                    "Sigma1" REAL,
                    "SecondaryEasting" REAL,
                    "Sigma2" REAL,
                    "SecondaryNorthing" REAL,
                    "Sigma3" REAL,
                    "DeltaEprimarytosecondary" REAL,
                    "DeltaNprimarytosecondary" REAL,
                    "Rangeprimarytosecondary" REAL,
                    "RangetoPrePlot" REAL,
                    "BrgtoPrePlot" REAL,
                    "PrimaryElevation" REAL,
                    "Sigma4" REAL,
                    "SecondaryElevation" REAL,
                    "Sigma5" REAL,
                    "Quality" TEXT,
                    "ROV1" TEXT,
                    "TimeStamp1" TEXT,
                    "PrimaryEasting1" REAL,
                    "Sigma6" REAL,
                    "PrimaryNorthing1" REAL,
                    "Sigma7" REAL,
                    "SecondaryEasting1" REAL,
                    "Sigma8" REAL,
                    "SecondaryNorthing1" REAL,
                    "Sigma9" REAL,
                    "DeltaEprimarytosecondary1" REAL,
                    "DeltaNprimarytosecondary1" REAL,
                    "Rangeprimarytosecondary1" REAL,
                    "RangetoPrePlot1" REAL,
                    "BrgtoPrePlot1" REAL,
                    "PrimaryElevation1" REAL,
                    "Sigma10" REAL,
                    "SecondaryElevation1" REAL,
                    "Sigma11" REAL,
                    "Quality1" TEXT,
                    "DeployedtoRetrievedEasting" REAL,
                    "DeployedtoRetrievedNorthing" REAL,
                    "DeployedtoRecoveredElevation" REAL,
                    "DeployedtoRetrievedRange" REAL,
                    "DeployedtoRetrievedBrg" REAL,
                    "Comments" TEXT,
                    "LinePoint" INTEGER,
                    "RecIdx" INTEGER DEFAULT 1,
                    "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    "Year" INTEGER,
                    "Month" INTEGER,
                    "Week" INTEGER,
                    "Day" TEXT,
                    "JDay" INTEGER DEFAULT 0,
                    "Date1" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    "Year1" INTEGER,
                    "Month1" INTEGER,
                    "Week1" INTEGER,
                    "Day1" TEXT,
                    "JDay1" INTEGER DEFAULT 0,
                    "DepTime" INTEGER,
                    "RecTime" INTEGER,
                    "PointComment" TEXT,
                    "REC_ID" INTEGER,
                    "NODE_ID" INTEGER,
                    "DEPLOY" INTEGER,
                    "RPI" INTEGER,
                    "PART_NO" INTEGER,
                    "RPRE_X" REAL,
                    "RPRE_Y" REAL,
                    "RFIELD_X" REAL,
                    "RFIELD_Y" REAL,
                    "RFIELD_Z" REAL,
                    "REC_X" REAL,
                    "REC_Y" REAL,
                    "REC_Z" REAL,
                    "TIMECORR" REAL,
                    "BULKSHFT" REAL,
                    "QDRIFT" REAL,
                    "LDRIFT" REAL,
                    "TRIMPTCH" REAL,
                    "TRIMROLL" REAL,
                    "TRIMYAW" REAL,
                    "PITCHFIN" REAL,
                    "ROLLFIN" REAL,
                    "YAWFIN" REAL,
                    "TOTDAYS" REAL,
                    "RECCOUNT" INTEGER,
                    "CLKFLAG" INTEGER,
                    "EC1_RUS0" REAL DEFAULT 0,
                    "EC1_RUS1" REAL DEFAULT 0,
                    "EC1_EDT0" REAL DEFAULT 0,
                    "EC1_EDT1" REAL DEFAULT 0,
                    "EC1_EPT0" REAL DEFAULT 0,
                    "EC1_EPT1" REAL DEFAULT 0,
                    "NODSTART" INTEGER DEFAULT 0,
                    "DEPLOYTM" INTEGER DEFAULT 0,
                    "PICKUPTM" INTEGER DEFAULT 0,
                    "RUNTIME" INTEGER DEFAULT 0,
                    "EC2_CD1" INTEGER DEFAULT 0,
                    "TOTSHOTS" INTEGER DEFAULT 0,
                    "TOTPROD" INTEGER DEFAULT 0,
                    "SPSK" INTEGER DEFAULT 0,
                    "TIER" INTEGER DEFAULT 1,
                    "isExported" INTEGER DEFAULT 0,
                    "isRecExported" INTEGER DEFAULT 0,
                    "Area" TEXT,
                    "RemoteUnit" TEXT,
                     "AUQRCode" TEXT,
                     "AURFID" TEXT,
                     "CUSerialNumber" TEXT,
                     "Status" TEXT,
                     "DeploymentType" TEXT,
                     "StartTimeEpoch" INTEGER,
                     "StartTimeUTC" TEXT,
                     "DeployTimeEpoch" INTEGER,
                     "DeployTimeUTC" TEXT,
                     "PickupTimeEpoch" INTEGER,
                     "PickupTimeUTC" TEXT,
                     "StopTimeEpoch" INTEGER,
                     "StopTimeUTC" TEXT,
                     "SPSX" REAL,
                     "SPSY" REAL,
                     "SPSZ" REAL,
                     "ActualX" REAL,
                     "ActualY" REAL,
                     "ActualZ" REAL,
                     "Deployed" TEXT,
                     "PickedUp" TEXT,
                     "Archived" TEXT,
                     "DeviceID" INTEGER,
                     "BinID" INTEGER,
                     "ExpectedTraces" INTEGER,
                     "CollectedTraces" INTEGER,
                     "DownloadedDatainMB" INTEGER,
                     "ExpectedDatainMB" INTEGER,
                     "DownloadError" INTEGER
              );
--create black box table (rov_box)
CREATE TABLE  IF NOT EXISTS  rov_box (
               "ID" INTEGER PRIMARY KEY,
               "TimeStamp" TEXT,
               VesselEasting REAL,
               VesselNorthing REAL ,
               VesselElevation REAL,
               VesselHDG REAL,
               VesselSOG REAL,
               VesselCOG REAL,
               ROV1_INS_Easting REAL,
               ROV1_INS_Northing REAL,
               ROV1_USBL_Easting REAL,
               ROV1_USBL_Northing REAL,
               ROV1Depth REAL,
               ROV1HDG REAL,
               ROV1SOG REAL,
               ROV1COG REAL,
               ROV1_TMS_Easting REAL,
               ROV1_TMS_Northing REAL,
               ROV1_TMS_Depth REAL,
               ROV2_INS_Easting REAL,
               ROV2_INS_Northing REAL,
               ROV2_USBL_Easting REAL,
               ROV2_USBL_Northing REAL,
               ROV2Depth REAL,
               ROV2HDG REAL,
               ROV2SOG REAL,
               ROV2COG REAL,
               ROV2_TMS_Easting REAL,
               ROV2_TMS_Northing REAL,
               ROV2_TMS_Depth REAL,
               Crane_Easting REAL,
               Crane_Northing REAL,
               Crane_Depth REAL,
               GNSS1_NOS INTEGER,
               GNSS1_DiffAge REAL,
               GNSS1_FixQuality INTEGER,
               GNSS1_HDOP REAL,
               GNSS1_PDOP REAL,
               GNSS1_VDOP REAL,
               GNSS2_NOS INTEGER,
               GNSS2_DiffAge REAL,
               GNSS2_FixQuality INTEGER,
               GNSS2_HDOP REAL,
               GNSS2_PDOP REAL,
               GNSS2_VDOP REAL,
               ROV1_PITCH REAL,
               ROV1_ROLL REAL,
               ROV2_PITCH REAL,
               ROV2_ROLL REAL,
               "Vessel" TEXT,
               "ROV1" TEXT,
               "ROV2" TEXT,
               "GNSS1" TEXT,
               "GNSS2" TEXT,
               "FileName" Text);
--Create Source Solution
CREATE TABLE  IF NOT EXISTS  SLSolution (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PPLine_FK INTEGER DEFAULT 0,
        File_FK INTEGER,
        LineName TEXT UNIQUE,
        Line INTEGER,
        Seq INTEGER,
        Attempt TEXT,
        Tier INTEGER,
        TierLine INTEGER,
        FSP INTEGER,
        LSP INTEGER,
        FGSP INTEGER,
        LGSP INTEGER,
        StartX DOUBLE,
        StartY DOUBLE,
        EndX DOUBLE,
        EndY DOUBLE,
        Vessel Text,
        Start_Time DATETIME,
        End_Time DATETIME,
        Start_Production_Time DATETIME,
        End_Production_Time DATETIME,
        PercentOfLineDone REAL,
        SeqProdCount REAL,
        PercentOfSeqDone REAL,
        Count_All INTEGER,
        Count_A INTEGER,
        Count_P INTEGER,
        Count_L INTEGER,
        Count_R INTEGER,
        Count_X INTEGER,
        Count_M INTEGER,
        Count_K INTEGER,
        Count_W INTEGER,
        Count_T INTEGER,
        FileName_FK INTEGER,
        FOREIGN KEY (PPLine_FK) REFERENCES SLPreplot(ID)  ON UPDATE CASCADE,
        FOREIGN KEY (FileName_FK) REFERENCES Files(ID) ON DELETE CASCADE ON UPDATE CASCADE,
        UNIQUE(LineName, ID));
CREATE TABLE  IF NOT EXISTS  SPSolution (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LineName_FK INTEGER,
    PPLine_FK INTEGER,
    PP_Point_FK INTEGER,
    FileName_FK INTEGER,
    Tier INTEGER DEFAULT 0,
    TierLinePoint INTEGER DEFAULT 0,
    LinePoint INTEGER DEFAULT 0,
    Point INTEGER DEFAULT 0,
    PointIdx INTEGER,
    FireCode TEXT,
    ArrayNumber INTEGER,
    FCodeIdx INTEGER DEFAULT 0,
    PointCode TEXT,
    Static REAL DEFAULT 0,
    PointDepth REAL DEFAULT 0,
    Datum INTEGER DEFAULT 0,
    Uphole REAL DEFAULT 0,
    WaterDepth INTEGER DEFAULT 0,
    Easting REAL DEFAULT 0,
    Northing REAL DEFAULT 0,
    Elevation REAL DEFAULT 0,
    JDay INTEGER DEFAULT 0,
    Hour INTEGER DEFAULT 0,
    Minute INTEGER DEFAULT 0,
    Second INTEGER DEFAULT 0,
    Microsecond REAL DEFAULT 0,
    Month INTEGER DEFAULT 0,
    Week INTEGER DEFAULT 0,
    Day INTEGER DEFAULT 0,
    Year INTEGER DEFAULT 0,
    YearDay TEXT,
    TimeStamp DATETIME,
    Vessel TEXT,
    RadialOffset REAL DEFAULT 0,
    ILOffset REAL DEFAULT 0,
    XLOffset REAL DEFAULT 0,
    isCompared INTEGER DEFAULT 0,
    isInSpec INTEGER DEFAULT 0,
    isILInSpec INTEGER DEFAULT 0,
    isXLInSpec INTEGER DEFAULT 0,
    PP_X REAL DEFAULT 0,
    PP_Y REAL DEFAULT 0,
    dX REAL DEFAULT 0,
    dY REAL DEFAULT 0,
    isPreplotCompared INTEGER DEFAULT 0,
    Spare1 INTEGER DEFAULT 0,
    Spare2 INTEGER DEFAULT 0,
    Spare3 INTEGER DEFAULT 0,
    UNIQUE(ID),
    FOREIGN KEY (LineName_FK) REFERENCES SLSolution(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PPLine_FK) REFERENCES SLPreplot(ID)  ON UPDATE CASCADE,
    FOREIGN KEY (PP_Point_FK) REFERENCES SPPreplot(ID) ON UPDATE CASCADE,
    FOREIGN KEY (FileName_FK) REFERENCES Files(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
--Create Receiver Solution
CREATE TABLE  IF NOT EXISTS  RLSolution (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PPLine_FK INTEGER,
        File_FK INTEGER,
        LineName TEXT,
        Line INTEGER,
        LineSolution INTEGER NOT NULL,
        Seq INTEGER DEFAULT 1,
        Attempt TEXT,
        Tier INTEGER,
        TierLine INTEGER,
        FRP INTEGER,
        LRP INTEGER,
        StartX REAL DEFAULT 0,
        StartY REAL DEFAULT 0,
        EndX REAL DEFAULT 0,
        EndY REAL DEFAULT 0,
        SRP INTEGER,
        ERP INTEGER,
        Vessel Text,
        StartYear INTEGER,
        StartMonth INTEGER,
        StartJDay INTEGER,
        StartDay INTEGER,
        StartHour INTEGER,
        StartMinute INTEGER,
        StartSecond INTEGER,
        StartMSecond REAL,
        EndYear INTEGER,
        EndMonth INTEGER,
        EndJDay INTEGER,
        EndDay INTEGER,
        EndHour INTEGER,
        EndMinute INTEGER,
        EndSecond REAL,
        EndMSecond REAL,
        Solution_FK INTEGER,
        PercentOfLineDone REAL,
        SeqProdCount REAL,
        PercentOFSeqDone REAL,
        Count_All INTEGER DEFAULT 0,
        is_clicked INTEGER DEFAULT 0,
        is_recovered INTEGER DEFAULT 0,
        is_fbloaded INTEGER DEFAULT 0,
        FileName_FK INTEGER,
        FOREIGN KEY (PPLine_FK) REFERENCES RLPreplot(ID) ON DELETE CASCADE,
        FOREIGN KEY (Solution_FK) REFERENCES Solutions(ID) ON DELETE CASCADE,
        FOREIGN KEY (FileName_FK) REFERENCES Files(ID) ON DELETE CASCADE,
        UNIQUE(LineSolution),
        UNIQUE(ID,LineSolution));
CREATE TABLE  IF NOT EXISTS  RPSolution (
       	ID INTEGER PRIMARY KEY AUTOINCREMENT,
       	LineName_FK	INTEGER,
       	Line INTEGER,
       	PP_Point_FK INTEGER,
       	PP_Line_FK INTEGER,
       	File_FK INTEGER,
       	Solution_FK INTEGER,
	    Tier INTEGER DEFAULT 0,
	    TierLinePoint INTEGER DEFAULT 0,
	    LinePoint INTEGER DEFAULT 0,
	    LinePointIdx INTEGER DEFAULT 0,
	    LinePointIdxSol INTEGER NOT NULL,
	    Point INTEGER DEFAULT 0,
	    PointIdx INTEGER,
	    FireCode TEXT,
	    Seq INTEGER DEFAULT 1,
	    ArrayNumber	INTEGER,
	    FCodeIdx INTEGER DEFAULT 0,
	    PointCode TEXT,
	    Static REAL DEFAULT 0,
	    PointDepth REAL DEFAULT 0,
	    Datum INTEGER DEFAULT 0,
	    Uphole REAL DEFAULT 0,
	    WaterDepth INTEGER DEFAULT 0,
	    Easting REAL DEFAULT 0,
	    Northing REAL DEFAULT 0,
	    Elevation REAL DEFAULT 0,
	    JDay INTEGER DEFAULT 0,
	    Hour INTEGER DEFAULT 0,
	    Minute INTEGER DEFAULT 0,
	    Second INTEGER DEFAULT 0,
	    Msecond REAL DEFAULT 0,
	    Month INTEGER DEFAULT 0,
	    Week INTEGER DEFAULT 0,
	    Day INTEGER DEFAULT 0,
	    Year INTEGER DEFAULT 0,
	    TimeStamp TEXT,
	    Date DATETIME,
	    YearDay TEXT,
		Vessel TEXT,
	    RadialOffset REAL DEFAULT 0,
	    ILOffset REAL DEFAULT 0,
	    XLOffset REAL DEFAULT 0,
	    isCompared	INTEGER DEFAULT 0,
	    isInSpec	INTEGER DEFAULT 0,
	    isILInSpec	INTEGER DEFAULT 0,
	    isXLInSpec	INTEGER DEFAULT 0,
	    PP_X REAL DEFAULT 0,
		PP_Y REAL DEFAULT 0,
	    dX REAL DEFAULT 0,
	    dY REAL DEFAULT 0,
	    isPreplotCompared INTEGER DEFAULT 0,
	    NODE_ID TEXT,
        DEPLOY INTEGER DEFAULT 1,
        RPI INTEGER DEFAULT 1,
        REC_X REAL DEFAULT 0,
        REC_Y REAL DEFAULT 0,
        REC_Z REAL DEFAULT 0,

        NEARILIN INTEGER DEFAULT 0,
        NEARXLIN INTEGER DEFAULT 0,
        TIMECORR  REAL DEFAULT 0,
        BULKSHIFT REAL DEFAULT 0,
        TIMINGEQ REAL DEFAULT 0,
        QDRIFT REAL DEFAULT 0,
        LDRIFT REAL DEFAULT 0,
        TRIMPTCH REAL DEFAULT 0,
        TRIMROLL REAL DEFAULT 0,
        TRIMYAW REAL DEFAULT 0,
        PITCHFIN REAL DEFAULT 0,
        ROLLFIN REAL DEFAULT 0,
        YAWFIN REAL DEFAULT 0,
        TOTDAYS REAL DEFAULT 0,
        NODSTART INTEGER DEFAULT 0,
        DEPLOYTM INTEGER DEFAULT 0,
        PICKUPTM INTEGER DEFAULT 0,
        RUNTIME  INTEGER DEFAULT 0,
        EC2_CD1 INTEGER DEFAULT 0,
        CLKFLAG INTEGER DEFAULT 0,
        EC1_RUS0 REAL DEFAULT 0,
        EC1_RUS1 REAL DEFAULT 0,
        EC1_EDT0 REAL DEFAULT 0,
        EC1_EDT1 REAL DEFAULT 0,
        EC1_EPT0 REAL DEFAULT 0,
        EC1_EPT1 REAL DEFAULT 0,
        TOTSHOTS INTEGER DEFAULT 0,
        TOTPROD INTEGER DEFAULT 0,
        SPSK INTEGER DEFAULT 0,
     	Spare1	INTEGER DEFAULT 0,
	    Spare2	INTEGER DEFAULT 0,
	    Spare3	INTEGER DEFAULT 0,
	    UNIQUE(LinePointIdxSol),
		UNIQUE(ID,LinePointIdxSol),
		FOREIGN KEY (LineName_FK) REFERENCES RLSolution(ID) ON DELETE CASCADE,
		FOREIGN KEY (PP_Point_FK) REFERENCES RPPreplot(ID) ON DELETE CASCADE,
		FOREIGN KEY (Solution_FK) REFERENCES Solutions(ID) ON DELETE CASCADE,
		FOREIGN KEY (PP_Line_FK) REFERENCES RLPreplot(ID) ON DELETE CASCADE,
		FOREIGN KEY (File_FK) REFERENCES Files(ID) ON DELETE CASCADE);
CREATE TABLE  IF NOT EXISTS  CSVLayers (
    ID INTEGER PRIMARY KEY,
    Name TEXT,
    Points INTEGER,
    Attr1Name TEXT,
    Attr2Name TEXT,
    Attr3Name TEXT,
    Comments TEXT
);
CREATE TABLE  IF NOT EXISTS  CSVpoints (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Layer_FK INTEGER,
    Point TEXT,
    X REAL,
    Y REAL,
    Z REAL,
    Attr1 REAL,
    Attr2 REAL,
    Attr3 REAL,
    FOREIGN KEY (Layer_FK) REFERENCES CSVLayer(ID) ON DELETE CASCADE);
CREATE VIEW IF NOT EXISTS PreplotSummaryAllFiles AS

SELECT
  'RLPreplot' AS TableName,

  (SELECT COUNT(*) FROM RLPreplot) AS LinesCount,
  (SELECT SUM(COALESCE(Points,0)) FROM RLPreplot) AS TotalPoints,
  (SELECT ROUND(AVG(COALESCE(Points,0)),2) FROM RLPreplot) AS AvgPointsPerLine,
  (SELECT ROUND(AVG(COALESCE(RealLineLength,0)),2) FROM RLPreplot) AS AvgRealLineLength,

  (SELECT MIN(Line) FROM RLPreplot) AS MinLine,
  (SELECT MAX(Line) FROM RLPreplot) AS MaxLine,

  (SELECT COUNT(DISTINCT File_FK) FROM RLPreplot) AS FilesCount,

  (SELECT GROUP_CONCAT(FileName, '; ')
     FROM (
       SELECT DISTINCT COALESCE(f.FileName, 'NULL') AS FileName
       FROM RLPreplot r
       LEFT JOIN Files f ON f.ID = r.File_FK
       ORDER BY FileName
     )
  ) AS FileNames,

  (SELECT Line FROM RLPreplot ORDER BY COALESCE(Points,0) DESC, ID ASC LIMIT 1) AS LongestPointsLine,
  (SELECT COALESCE(Points,0) FROM RLPreplot ORDER BY COALESCE(Points,0) DESC, ID ASC LIMIT 1) AS LongestPoints,

  (SELECT Line FROM RLPreplot
     ORDER BY (COALESCE(Points,0)=0), COALESCE(Points,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestPointsLine,
  (SELECT COALESCE(Points,0) FROM RLPreplot
     ORDER BY (COALESCE(Points,0)=0), COALESCE(Points,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestPoints,

  (SELECT Line FROM RLPreplot ORDER BY COALESCE(RealLineLength,0) DESC, ID ASC LIMIT 1) AS LongestLengthLine,
  (SELECT COALESCE(RealLineLength,0) FROM RLPreplot ORDER BY COALESCE(RealLineLength,0) DESC, ID ASC LIMIT 1) AS LongestLength,

  (SELECT Line FROM RLPreplot
     ORDER BY (COALESCE(RealLineLength,0)=0), COALESCE(RealLineLength,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestLengthLine,
  (SELECT COALESCE(RealLineLength,0) FROM RLPreplot
     ORDER BY (COALESCE(RealLineLength,0)=0), COALESCE(RealLineLength,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestLength

UNION ALL

SELECT
  'SLPreplot' AS TableName,

  (SELECT COUNT(*) FROM SLPreplot) AS LinesCount,
  (SELECT SUM(COALESCE(Points,0)) FROM SLPreplot) AS TotalPoints,
  (SELECT ROUND(AVG(COALESCE(Points,0)),2) FROM SLPreplot) AS AvgPointsPerLine,
  (SELECT ROUND(AVG(COALESCE(RealLineLength,0)),2) FROM SLPreplot) AS AvgRealLineLength,

  (SELECT MIN(Line) FROM SLPreplot) AS MinLine,
  (SELECT MAX(Line) FROM SLPreplot) AS MaxLine,

  (SELECT COUNT(DISTINCT File_FK) FROM SLPreplot) AS FilesCount,

  (SELECT GROUP_CONCAT(FileName, '; ')
     FROM (
       SELECT DISTINCT COALESCE(f.FileName, 'NULL') AS FileName
       FROM SLPreplot s
       LEFT JOIN Files f ON f.ID = s.File_FK
       ORDER BY FileName
     )
  ) AS FileNames,

  (SELECT Line FROM SLPreplot ORDER BY COALESCE(Points,0) DESC, ID ASC LIMIT 1) AS LongestPointsLine,
  (SELECT COALESCE(Points,0) FROM SLPreplot ORDER BY COALESCE(Points,0) DESC, ID ASC LIMIT 1) AS LongestPoints,

  (SELECT Line FROM SLPreplot
     ORDER BY (COALESCE(Points,0)=0), COALESCE(Points,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestPointsLine,
  (SELECT COALESCE(Points,0) FROM SLPreplot
     ORDER BY (COALESCE(Points,0)=0), COALESCE(Points,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestPoints,

  (SELECT Line FROM SLPreplot ORDER BY COALESCE(RealLineLength,0) DESC, ID ASC LIMIT 1) AS LongestLengthLine,
  (SELECT COALESCE(RealLineLength,0) FROM SLPreplot ORDER BY COALESCE(RealLineLength,0) DESC, ID ASC LIMIT 1) AS LongestLength,

  (SELECT Line FROM SLPreplot
     ORDER BY (COALESCE(RealLineLength,0)=0), COALESCE(RealLineLength,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestLengthLine,
  (SELECT COALESCE(RealLineLength,0) FROM SLPreplot
     ORDER BY (COALESCE(RealLineLength,0)=0), COALESCE(RealLineLength,0) ASC, ID ASC
     LIMIT 1
  ) AS ShortestLength;


