# Generated by Django 5.2.8 on 2026-02-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('imo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('mmsi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('call_sign', models.CharField(blank=True, max_length=32, null=True)),
                ('vessel_type', models.CharField(blank=True, max_length=60, null=True)),
                ('owner', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
