# Generated by Django 5.2.8 on 2025-12-12 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_projectmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('SRC_SPS_1', 'Source SPS V1.0'), ('SRC_SPS_21', 'Source SPS v2.1'), ('REC_SPS', 'Receiver SPS  V1.0'), ('REC_SPS', 'Receiver SPS  V2.1'), ('HDR_SPS_1', 'Header SPS V1.0'), ('HDR_SPS_21', 'Header SPS V2.1')], max_length=16)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_files', to='core.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'file_type', 'file_name', '-uploaded_at'],
            },
        ),
    ]
