# Generated by Django 5.2.8 on 2025-12-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseproject', '0001_initial'),
        ('core', '0006_seed_sps_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprojectfile',
            name='sps_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_files', to='core.spsrevision'),
        ),
        migrations.AlterField(
            model_name='baseprojectfile',
            name='file_type',
            field=models.CharField(choices=[('SRC_SPS', 'Source SPS'), ('REC_SPS', 'Receiver SPS'), ('HDR_SPS', 'Header SPS')], max_length=16),
        ),
    ]
