# Generated by Django 5.2.8 on 2026-03-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseproject', '0002_baseprojectfile_sps_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id_ref', models.IntegerField(blank=True, null=True)),
                ('username_text', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
                ('module_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx'), models.Index(fields=['level'], name='audit_log_level_6d4c28_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['project_name'], name='audit_log_project_148eab_idx'), models.Index(fields=['username_text'], name='audit_log_usernam_67ff69_idx'), models.Index(fields=['request_id'], name='audit_log_request_a46c86_idx')],
            },
        ),
    ]
